export { apiClient } from './client'
export { authApi } from './auth'
export { householdsApi } from './households'
export { tasksApi } from './tasks'
export { noticesApi } from './notices'
export { shoppingApi } from './shopping'

export type { User, AuthResponse } from './auth'
export type { Household, HouseholdMember, HouseholdInvite } from './households'
export type { Task, TaskType } from './tasks'
export type { Notice, NoticePriority } from './notices'
export type { ShoppingList, ShoppingItem } from './shopping'
